### ISSUE TITLE
"ImportError: cannot import name 'getargspec' from 'inspect'" on a generic install

### ISSUE THREAD

**Issue by wojtekwtf** [a16z/farcaster-py#491]
## 🐛 Bug Report

I was trying to use the package but it fails at the very first interaction. This is the result of running the healthcheck on a generic example from readme

```
(farcaster-analytics) ➜  farcaster-analytics python main.py                                                                                     
Traceback (most recent call last):
  File "/Users/wojciechkulikowski/projects/farcaster-analytics/main.py", line 2, in <module>
    from farcaster import Warpcast
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/farcaster/__init__.py", line 5, in <module>
    from .client import Warpcast  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/farcaster/client.py", line 9, in <module>
    from eth_account.account import Account
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_account/account.py", line 71, in <module>
    from eth_account.messages import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_account/messages.py", line 25, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/__init__.py", line 3, in <module>
    from eth_abi.abi import (  # NOQA
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/Users/wojciechkulikowski/.local/share/virtualenvs/farcaster-analytics-Dcob0k81/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py)
```

## 🔬 How To Reproduce

Follow README, try to run the health check

### Code sample

```
from farcaster import Warpcast

client = Warpcast(mnemonic="<valid mnemonic>")

print(client.get_healthcheck())
```

### Environment

* OS: macOS
* Python version: 3.11.2

**Comment by wojtekwtf** [comment]
@kevinj507 fyi this is using warpcast api, and moving to hubs is recommended

afaik there is no python alternative to fetching data from hubs yet

**Comment by fmhall** [comment]
@wojtekwtf @kevinj507 Unfortunately, 3.11 is not supported right now due to this awful package, `parsimonious`. I'm working on a fix
